/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "INAP"
 * 	found in "INAP_DEF.asn"
 */

#ifndef	_ConnectArg_H_
#define	_ConnectArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DestinationRoutingAddress.h"
#include "CutAndPaste.h"
#include "CallingPartyNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConnectArg */
typedef struct ConnectArg {
	DestinationRoutingAddress_t	 destinationRoutingAddress;
	CutAndPaste_t	*cutAndPaste	/* OPTIONAL */;
	CallingPartyNumber_t	*callingPartyNumber	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectArg;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectArg_H_ */
#include <asn_internal.h>
