/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "INAP"
 * 	found in "INAP_DEF.asn"
 */

#include "ConnectArg.h"

static asn_TYPE_member_t asn_MBR_ConnectArg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectArg, destinationRoutingAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DestinationRoutingAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"destinationRoutingAddress"
		},
	{ ATF_POINTER, 2, offsetof(struct ConnectArg, cutAndPaste),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CutAndPaste,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cutAndPaste"
		},
	{ ATF_POINTER, 1, offsetof(struct ConnectArg, callingPartyNumber),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallingPartyNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingPartyNumber"
		},
};
static ber_tlv_tag_t asn_DEF_ConnectArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ConnectArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* destinationRoutingAddress */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* cutAndPaste */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 2, 0, 0 } /* callingPartyNumber */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConnectArg_specs_1 = {
	sizeof(struct ConnectArg),
	offsetof(struct ConnectArg, _asn_ctx),
	asn_MAP_ConnectArg_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ConnectArg = {
	"ConnectArg",
	"ConnectArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ConnectArg_tags_1,
	sizeof(asn_DEF_ConnectArg_tags_1)
		/sizeof(asn_DEF_ConnectArg_tags_1[0]), /* 1 */
	asn_DEF_ConnectArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConnectArg_tags_1)
		/sizeof(asn_DEF_ConnectArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ConnectArg_1,
	3,	/* Elements count */
	&asn_SPC_ConnectArg_specs_1	/* Additional specs */
};

