/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "INAP"
 * 	found in "INAP_DEF.asn"
 */

#include "InitialDPArg.h"

static asn_TYPE_member_t asn_MBR_InitialDPArg_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitialDPArg, serviceKey),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serviceKey"
		},
	{ ATF_POINTER, 2, offsetof(struct InitialDPArg, calledPartyNumber),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CalledPartyNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"calledPartyNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct InitialDPArg, callingPartyNumber),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallingPartyNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callingPartyNumber"
		},
};
static ber_tlv_tag_t asn_DEF_InitialDPArg_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_InitialDPArg_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* serviceKey */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* calledPartyNumber */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* callingPartyNumber */
};
static asn_SEQUENCE_specifics_t asn_SPC_InitialDPArg_specs_1 = {
	sizeof(struct InitialDPArg),
	offsetof(struct InitialDPArg, _asn_ctx),
	asn_MAP_InitialDPArg_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_InitialDPArg = {
	"InitialDPArg",
	"InitialDPArg",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_InitialDPArg_tags_1,
	sizeof(asn_DEF_InitialDPArg_tags_1)
		/sizeof(asn_DEF_InitialDPArg_tags_1[0]), /* 1 */
	asn_DEF_InitialDPArg_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitialDPArg_tags_1)
		/sizeof(asn_DEF_InitialDPArg_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_InitialDPArg_1,
	3,	/* Elements count */
	&asn_SPC_InitialDPArg_specs_1	/* Additional specs */
};

