/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "INAP"
 * 	found in "INAP_DEF.asn"
 */

#ifndef	_InitialDPArg_H_
#define	_InitialDPArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceKey.h"
#include "CalledPartyNumber.h"
#include "CallingPartyNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InitialDPArg */
typedef struct InitialDPArg {
	ServiceKey_t	 serviceKey;
	CalledPartyNumber_t	*calledPartyNumber	/* OPTIONAL */;
	CallingPartyNumber_t	*callingPartyNumber	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitialDPArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitialDPArg;

#ifdef __cplusplus
}
#endif

#endif	/* _InitialDPArg_H_ */
#include <asn_internal.h>
