/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "INAP"
 * 	found in "INAP_DEF.asn"
 */

#ifndef	_ReleaseCallArg_H_
#define	_ReleaseCallArg_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Cause.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ReleaseCallArg */
typedef Cause_t	 ReleaseCallArg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReleaseCallArg;
asn_struct_free_f ReleaseCallArg_free;
asn_struct_print_f ReleaseCallArg_print;
asn_constr_check_f ReleaseCallArg_constraint;
ber_type_decoder_f ReleaseCallArg_decode_ber;
der_type_encoder_f ReleaseCallArg_encode_der;
xer_type_decoder_f ReleaseCallArg_decode_xer;
xer_type_encoder_f ReleaseCallArg_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReleaseCallArg_H_ */
#include <asn_internal.h>
