################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../asn/AARE-apdu.c \
../asn/AARQ-apdu.c \
../asn/ABRT-apdu.c \
../asn/ABRT-source.c \
../asn/ANY.c \
../asn/Abort.c \
../asn/Associate-result.c \
../asn/Associate-source-diagnostic.c \
../asn/BIT_STRING.c \
../asn/BOOLEAN.c \
../asn/Begin.c \
../asn/CalledPartyNumber.c \
../asn/CallingPartyNumber.c \
../asn/Cause.c \
../asn/Component.c \
../asn/ComponentPortion.c \
../asn/ConnectArg.c \
../asn/Continue.c \
../asn/CutAndPaste.c \
../asn/DestTransactionID.c \
../asn/DestinationRoutingAddress.c \
../asn/Dialog1.c \
../asn/DialogueOC.c \
../asn/DialoguePDU.c \
../asn/DialoguePortion.c \
../asn/ERROR.c \
../asn/End.c \
../asn/ErrorCode.c \
../asn/ExternalPDU.c \
../asn/GeneralProblem.c \
../asn/INTEGER.c \
../asn/InitialDPArg.c \
../asn/Integer4.c \
../asn/Invoke.c \
../asn/InvokeIdType.c \
../asn/InvokeProblem.c \
../asn/NULL.c \
../asn/NativeEnumerated.c \
../asn/NativeInteger.c \
../asn/OBJECT_IDENTIFIER.c \
../asn/OCTET_STRING.c \
../asn/OPERATION.c \
../asn/OrigTransactionID.c \
../asn/P-AbortCause.c \
../asn/Parameter.c \
../asn/RLRE-apdu.c \
../asn/RLRQ-apdu.c \
../asn/Reason.c \
../asn/Reject.c \
../asn/Release-request-reason.c \
../asn/Release-response-reason.c \
../asn/ReleaseCallArg.c \
../asn/ReturnError.c \
../asn/ReturnErrorProblem.c \
../asn/ReturnResult.c \
../asn/ReturnResultProblem.c \
../asn/ServiceKey.c \
../asn/TCMessage.c \
../asn/Unidirectional.c \
../asn/asn_SEQUENCE_OF.c \
../asn/asn_SET_OF.c \
../asn/asn_codecs_prim.c \
../asn/ber_decoder.c \
../asn/ber_tlv_length.c \
../asn/ber_tlv_tag.c \
../asn/constr_CHOICE.c \
../asn/constr_SEQUENCE.c \
../asn/constr_SEQUENCE_OF.c \
../asn/constr_SET_OF.c \
../asn/constr_TYPE.c \
../asn/constraints.c \
../asn/der_encoder.c \
../asn/per_decoder.c \
../asn/per_encoder.c \
../asn/per_opentype.c \
../asn/per_support.c \
../asn/xer_decoder.c \
../asn/xer_encoder.c \
../asn/xer_support.c 

OBJS += \
./asn/AARE-apdu.o \
./asn/AARQ-apdu.o \
./asn/ABRT-apdu.o \
./asn/ABRT-source.o \
./asn/ANY.o \
./asn/Abort.o \
./asn/Associate-result.o \
./asn/Associate-source-diagnostic.o \
./asn/BIT_STRING.o \
./asn/BOOLEAN.o \
./asn/Begin.o \
./asn/CalledPartyNumber.o \
./asn/CallingPartyNumber.o \
./asn/Cause.o \
./asn/Component.o \
./asn/ComponentPortion.o \
./asn/ConnectArg.o \
./asn/Continue.o \
./asn/CutAndPaste.o \
./asn/DestTransactionID.o \
./asn/DestinationRoutingAddress.o \
./asn/Dialog1.o \
./asn/DialogueOC.o \
./asn/DialoguePDU.o \
./asn/DialoguePortion.o \
./asn/ERROR.o \
./asn/End.o \
./asn/ErrorCode.o \
./asn/ExternalPDU.o \
./asn/GeneralProblem.o \
./asn/INTEGER.o \
./asn/InitialDPArg.o \
./asn/Integer4.o \
./asn/Invoke.o \
./asn/InvokeIdType.o \
./asn/InvokeProblem.o \
./asn/NULL.o \
./asn/NativeEnumerated.o \
./asn/NativeInteger.o \
./asn/OBJECT_IDENTIFIER.o \
./asn/OCTET_STRING.o \
./asn/OPERATION.o \
./asn/OrigTransactionID.o \
./asn/P-AbortCause.o \
./asn/Parameter.o \
./asn/RLRE-apdu.o \
./asn/RLRQ-apdu.o \
./asn/Reason.o \
./asn/Reject.o \
./asn/Release-request-reason.o \
./asn/Release-response-reason.o \
./asn/ReleaseCallArg.o \
./asn/ReturnError.o \
./asn/ReturnErrorProblem.o \
./asn/ReturnResult.o \
./asn/ReturnResultProblem.o \
./asn/ServiceKey.o \
./asn/TCMessage.o \
./asn/Unidirectional.o \
./asn/asn_SEQUENCE_OF.o \
./asn/asn_SET_OF.o \
./asn/asn_codecs_prim.o \
./asn/ber_decoder.o \
./asn/ber_tlv_length.o \
./asn/ber_tlv_tag.o \
./asn/constr_CHOICE.o \
./asn/constr_SEQUENCE.o \
./asn/constr_SEQUENCE_OF.o \
./asn/constr_SET_OF.o \
./asn/constr_TYPE.o \
./asn/constraints.o \
./asn/der_encoder.o \
./asn/per_decoder.o \
./asn/per_encoder.o \
./asn/per_opentype.o \
./asn/per_support.o \
./asn/xer_decoder.o \
./asn/xer_encoder.o \
./asn/xer_support.o 

C_DEPS += \
./asn/AARE-apdu.d \
./asn/AARQ-apdu.d \
./asn/ABRT-apdu.d \
./asn/ABRT-source.d \
./asn/ANY.d \
./asn/Abort.d \
./asn/Associate-result.d \
./asn/Associate-source-diagnostic.d \
./asn/BIT_STRING.d \
./asn/BOOLEAN.d \
./asn/Begin.d \
./asn/CalledPartyNumber.d \
./asn/CallingPartyNumber.d \
./asn/Cause.d \
./asn/Component.d \
./asn/ComponentPortion.d \
./asn/ConnectArg.d \
./asn/Continue.d \
./asn/CutAndPaste.d \
./asn/DestTransactionID.d \
./asn/DestinationRoutingAddress.d \
./asn/Dialog1.d \
./asn/DialogueOC.d \
./asn/DialoguePDU.d \
./asn/DialoguePortion.d \
./asn/ERROR.d \
./asn/End.d \
./asn/ErrorCode.d \
./asn/ExternalPDU.d \
./asn/GeneralProblem.d \
./asn/INTEGER.d \
./asn/InitialDPArg.d \
./asn/Integer4.d \
./asn/Invoke.d \
./asn/InvokeIdType.d \
./asn/InvokeProblem.d \
./asn/NULL.d \
./asn/NativeEnumerated.d \
./asn/NativeInteger.d \
./asn/OBJECT_IDENTIFIER.d \
./asn/OCTET_STRING.d \
./asn/OPERATION.d \
./asn/OrigTransactionID.d \
./asn/P-AbortCause.d \
./asn/Parameter.d \
./asn/RLRE-apdu.d \
./asn/RLRQ-apdu.d \
./asn/Reason.d \
./asn/Reject.d \
./asn/Release-request-reason.d \
./asn/Release-response-reason.d \
./asn/ReleaseCallArg.d \
./asn/ReturnError.d \
./asn/ReturnErrorProblem.d \
./asn/ReturnResult.d \
./asn/ReturnResultProblem.d \
./asn/ServiceKey.d \
./asn/TCMessage.d \
./asn/Unidirectional.d \
./asn/asn_SEQUENCE_OF.d \
./asn/asn_SET_OF.d \
./asn/asn_codecs_prim.d \
./asn/ber_decoder.d \
./asn/ber_tlv_length.d \
./asn/ber_tlv_tag.d \
./asn/constr_CHOICE.d \
./asn/constr_SEQUENCE.d \
./asn/constr_SEQUENCE_OF.d \
./asn/constr_SET_OF.d \
./asn/constr_TYPE.d \
./asn/constraints.d \
./asn/der_encoder.d \
./asn/per_decoder.d \
./asn/per_encoder.d \
./asn/per_opentype.d \
./asn/per_support.d \
./asn/xer_decoder.d \
./asn/xer_encoder.d \
./asn/xer_support.d 


# Each subdirectory must supply rules for building sources it contributes
asn/%.o: ../asn/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I"/home/aalto/workspace/ProtoVSCP/asn" -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


